version: '3.8'
services:
  db:
    image: docker.io/postgres:15.10
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql:/tmp/sql:ro
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      start_period: 15s
    mem_limit: 1g
    networks:
      - demo

  fastapi:
    image: fastapidemo:latest
    environment:
      PGHOST: db
    ports:
      - 80:80
    networks:
      - demo

volumes:
  pg-data:
    driver: local

networks:
  demo: